/*
* Generated file
*
* Generated from: yang module name: learning-switch-impl yang module local name: learning-switch-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Feb 24 00:25:06 PST 2017
*
* Do not modify this file unless it is present under src/main directory
*/
package org.sdnhub.odl.tutorial.learningswitch.impl;
@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:sdnhub:odl:tutorial:learning-switch:learning-switch-impl", name = "learning-switch-impl", revision = "2015-06-05")

public abstract class AbstractTutorialLearningSwitchModuleFactory implements org.opendaylight.controller.config.spi.ModuleFactory {
    public static final java.lang.String NAME = "learning-switch-impl";

    private static final java.util.Set<Class<? extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface>> serviceIfcs;

    @Override
    public final String getImplementationName() {
        return NAME;
    }

    static {
        java.util.Set<Class<? extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface>> serviceIfcs2 = new java.util.HashSet<Class<? extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface>>();
        serviceIfcs = java.util.Collections.unmodifiableSet(serviceIfcs2);
    }

    @Override
    public final boolean isModuleImplementingServiceInterface(Class<? extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface> serviceInterface) {
        for (Class<?> ifc: serviceIfcs) {
            if (serviceInterface.isAssignableFrom(ifc)){
                return true;
            }
        }
        return false;
    }

    @Override
    public java.util.Set<Class<? extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface>> getImplementedServiceIntefaces() {
        return serviceIfcs;
    }

    @Override
    public org.opendaylight.controller.config.spi.Module createModule(String instanceName, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver, org.osgi.framework.BundleContext bundleContext) {
        return instantiateModule(instanceName, dependencyResolver, bundleContext);
    }

    @Override
    public org.opendaylight.controller.config.spi.Module createModule(String instanceName, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver, org.opendaylight.controller.config.api.DynamicMBeanWithInstance old, org.osgi.framework.BundleContext bundleContext) throws Exception {
        org.sdnhub.odl.tutorial.learningswitch.impl.TutorialLearningSwitchModule oldModule = null;
        try {
            oldModule = (org.sdnhub.odl.tutorial.learningswitch.impl.TutorialLearningSwitchModule) old.getModule();
        } catch(Exception e) {
            return handleChangedClass(old);
        }
        org.sdnhub.odl.tutorial.learningswitch.impl.TutorialLearningSwitchModule module = instantiateModule(instanceName, dependencyResolver, oldModule, old.getInstance(), bundleContext);
        module.setRpcRegistry(oldModule.getRpcRegistry());
        module.setDataBroker(oldModule.getDataBroker());
        module.setNotificationService(oldModule.getNotificationService());

        return module;
    }

    public org.sdnhub.odl.tutorial.learningswitch.impl.TutorialLearningSwitchModule instantiateModule(String instanceName, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver, org.sdnhub.odl.tutorial.learningswitch.impl.TutorialLearningSwitchModule oldModule, java.lang.AutoCloseable oldInstance, org.osgi.framework.BundleContext bundleContext) {
        return new org.sdnhub.odl.tutorial.learningswitch.impl.TutorialLearningSwitchModule(new org.opendaylight.controller.config.api.ModuleIdentifier(NAME, instanceName), dependencyResolver, oldModule, oldInstance);
    }

    public org.sdnhub.odl.tutorial.learningswitch.impl.TutorialLearningSwitchModule instantiateModule(String instanceName, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver, org.osgi.framework.BundleContext bundleContext) {
        return new org.sdnhub.odl.tutorial.learningswitch.impl.TutorialLearningSwitchModule(new org.opendaylight.controller.config.api.ModuleIdentifier(NAME, instanceName), dependencyResolver);
    }

    public org.sdnhub.odl.tutorial.learningswitch.impl.TutorialLearningSwitchModule handleChangedClass(org.opendaylight.controller.config.api.DynamicMBeanWithInstance old) throws Exception {
        throw new UnsupportedOperationException("Class reloading is not supported");
    }

    @Override
    public java.util.Set<org.sdnhub.odl.tutorial.learningswitch.impl.TutorialLearningSwitchModule> getDefaultModules(org.opendaylight.controller.config.api.DependencyResolverFactory dependencyResolverFactory, org.osgi.framework.BundleContext bundleContext) {
        return new java.util.HashSet<org.sdnhub.odl.tutorial.learningswitch.impl.TutorialLearningSwitchModule>();
    }

}
